### ISSUE TITLE
Chapter 1 - order of the exercises

### ISSUE THREAD

**Issue by liuxinyu95** [liuxinyu95/unplugged#10]
feedbacks: 
“头几道习题的安排是不是再要考虑一下。我试下来乘法交换律和结合律的证明难度不比加法交换律低，而且证乘法结合律我用到了分配律。也就是——也许加法交换律应该放正文，并且习题2、3顺序应该反一下？”

**Comment by liuxinyu95** [comment]
(1) first proof a.(b + c) = a.b + a.c
* c = 0, a.(b+0) = a.b = a.b + a.0
* suppose a.(b+c) = a.b + a.c holds, then 
   a.(b+c') 
= a.(b+c)'
= a.(b+c) + a
= a.b + a.c + a
= ab + a.c'
QED

(2) proof (a.b).c = a.(b.c)
* c = 0, (a.b).0 = 0 = a.0 = a.(b.0)
* suppose (a.b).c = a.(b.c) holds, then
(a.b).c' 
= (a.b).c + (a.b)
= a.(b.c) + a.(b.1)
= a.(b.c + b)
= a.(b.c')
QED

**Comment by liuxinyu95** [comment]
Will change the order of the exercise, and I am considering add an appendix of answers to some problems

**Comment by EzioL** [comment]
https://github.com/EzioL/unplugged-exercises/blob/master/1.1-%E8%AF%81%E6%98%8E%E4%B9%98%E6%B3%95%E7%9A%84%E5%88%86%E9%85%8D%E5%BE%8B%EF%BC%8C%E7%BB%93%E5%90%88%E5%BE%8B%E5%92%8C%E4%BA%A4%E6%8D%A2%E5%BE%8B.md

**Comment by liuxinyu95** [comment]
https://github.com/liuxinyu95/unplugged/blob/master/appendix/answer/ans-zh-cn.tex#L182
