### ISSUE TITLE
Chapter 3, Page56 

### ISSUE THREAD

**Issue by R4mble** [liuxinyu95/unplugged#11]
![image](https://user-images.githubusercontent.com/28989448/56860935-865e0980-69ce-11e9-8c0e-090f44d4b096.png)

Chapter 3, Page 56
1. 否则
2. 两个奇数的和应该是偶数

**Comment by liuxinyu95** [comment]
非常感谢，我会马上修改

**Comment by liuxinyu95** [comment]
已修正：
https://github.com/liuxinyu95/unplugged/commit/ddc472bbcf33a8155e99f002512448629aac69b0
