### ISSUE TITLE
「国际语」

### ISSUE THREAD

**Issue by adah1972** [liuxinyu95/unplugged#12]
第一次看到中文第 10 页上的「国际语」时，我愣了一下，感觉这个词好陌生啊（以前听到过世界语）。查了下才知道国际语（Interlingua）和世界语（Esperanto）还不是一个东西。

建议对这样的特殊词加上括号标注原文，甚至进一步加个注，避免读者的误解。如：

> 这门语言后来被称 为“国际语”（Interlingua，注意国际语和世界语是两种不同的人造语言）。

**Comment by liuxinyu95** [comment]
非常感谢，已经做了相应的修改：
https://github.com/liuxinyu95/unplugged/commit/cd152fc49e6d4efe1e6a5f4146c97c6bcf8d7c2d
