### ISSUE TITLE
Automatic PDF generation

### ISSUE THREAD

**Issue by drupol** [liuxinyu95/unplugged#15]
Hello, 

Would you be interested into continuous builds that automatically builds PDFs ? Like in this [project](https://github.com/hmemcpy/milewski-ctfp-pdf)?

See the related PR: https://github.com/hmemcpy/milewski-ctfp-pdf/pull/251

I guess it should be pretty similar for this project.

What do you think?

Thanks.

**Comment by liuxinyu95** [comment]
Hi,

This is great idea! I love This CD mechanism to auto build new PDFs upon any new commits.

**Comment by drupol** [comment]
Great!

I'll submit a PR tonight (UTC+2) most probably.

**Comment by liuxinyu95** [comment]
Hi,

I defined default font for different OS:
\def\macmainfont{STSong} % Under Mac OS X
\def\macboldfont{STHeiti}
\def\macmonofont{Monaco}
\def\winmainfont{SimSun} % Under Windows
\def\winboldfont{SimHei}
\def\winmonofont{Consolas}
\def\linuxmainfont{WenQuanYi Micro Hei} % Under Linux
\def\linuxboldfont{WenQuanYi Zen Hei}
\def\linuxmainfont{Courier}

If the auto-build is in Ubuntu Linux, I suggest to use WenQuanYi as the default font, and we may needn't add the fonts folder.

**Comment by liuxinyu95** [comment]
https://github.com/liuxinyu95/unplugged/actions

**Comment by drupol** [comment]
OOooh ! Great ! I see that you made some updates! Super :+1:

**Comment by drupol** [comment]
If you want we can create a pre-release for each commit so we have new PDFs generated every time a commit is made.
