### ISSUE TITLE
preface-en.tex sometimes misspells "secret" as "secrete"

### ISSUE THREAD

**Issue by Andrew-Cottrell** [liuxinyu95/unplugged#16]
https://github.com/liuxinyu95/unplugged/blob/612fbf8b02685aa8521eb10ad95ed19f41d92ba2/appendix/preface/preface-en.tex#L104

https://github.com/liuxinyu95/unplugged/blob/612fbf8b02685aa8521eb10ad95ed19f41d92ba2/appendix/preface/preface-en.tex#L128

https://github.com/liuxinyu95/unplugged/blob/612fbf8b02685aa8521eb10ad95ed19f41d92ba2/appendix/preface/preface-en.tex#L159

**Comment by liuxinyu95** [comment]
Thanks a lot! I did a scan and fixed similar typos:
https://github.com/liuxinyu95/unplugged/commit/12996d24c4b4922d4e8704001d0ce1c49aff25d5
I'll update the PDF next.

**Comment by liuxinyu95** [comment]
PDF updated
