### ISSUE TITLE
Chapter 2  - 勘误

### ISSUE THREAD

**Issue by JulianZhang** [liuxinyu95/unplugged#21]
https://github.com/liuxinyu95/unplugged/blob/b6348f3189ad1721932a81838027891d34af4dc9/recursion/recursion-zh-cn.tex#L490

现在的内容是
若$x > 0$、$y < 0$，我们需要倒满瓶子$A$共$x$次，倒空瓶子$B$共$y$次；反之若$x < 0$、$y > 0$，则需要倒空瓶子$A$共$x$次，倒空瓶子$B$共$y$次。
应该是
若$x > 0$、$y < 0$，我们需要倒满瓶子$A$共$x$次，倒空瓶子$B$共$y$次；反之若$x < 0$、$y > 0$，则需要倒空瓶子$A$共$x$次，倒**满**瓶子$B$共$y$次。

**Comment by liuxinyu95** [comment]
非常感谢！的确是错误。我稍后马上修改。

**Comment by liuxinyu95** [comment]
提交了修改：
https://github.com/liuxinyu95/unplugged/commit/3709fc63e51179d92739b3ff6d287a8d44fa22b6
