### ISSUE TITLE
第六章 勘误

### ISSUE THREAD

**Issue by chirsz-ever** [liuxinyu95/unplugged#25]
https://github.com/liuxinyu95/unplugged/blob/71b3252cd20b5e5b1f5b0f800e9dc869784d5da7/infinity/infinity-zh-cn.tex#L36
https://github.com/liuxinyu95/unplugged/blob/71b3252cd20b5e5b1f5b0f800e9dc869784d5da7/infinity/infinity-zh-cn.tex#L993
此两处将 Dedekind 翻译为“戴得金”，其它处翻译都是“戴德金”

**Comment by liuxinyu95** [comment]
多谢指出！已改正：
https://github.com/liuxinyu95/unplugged/commit/de8152517b92e68661b347a1a89c9233873cc1f4
