### ISSUE TITLE
(solved) problem with fonts

### ISSUE THREAD

**Issue by EmanueleRaineri** [liuxinyu95/unplugged#34]
Dear Liu Xinyu, 

thanks for making your book available on GitHub.
I had a few (now solved) problems compiling it under Ubuntu. I am not claiming 
there's any problem with your code, but I leave a note here just in case it can help
other readers. 
Essentially when doing `make en` Latex was trying to use Windows fonts even
when running under Linux; hence the compilation stopped as it could not _eg_ find `Consolas`, etc...

To fix this, I commented out 3 lines in `prelude.sty` and replaced them as follows:
```
%\def\winmainfont{SimSun} % Under Windows
\def\winmainfont{WenQuanYi Micro Hei}
%\def\winboldfont{SimHei}
%\def\winmonofont{Consolas}
\def\winboldfont{WenQuanYi Zen Hei}
\def\winmonofont{Courier}
```

**Comment by liuxinyu95** [comment]
Hi,

Thanks for raising this issue. I realized there were errors in font configuration.
I made some fixing:
https://github.com/liuxinyu95/unplugged/commit/22b550932c1dc2c3f8600d99c8b94aa2734a9ba0

Feel free to pull and check again.

Thanks

**Comment by EmanueleRaineri** [comment]
Seems to work now, thanks

E
