### ISSUE TITLE
Double "and" in line 222 of preface-en.tex

### ISSUE THREAD

**Issue by mcpinto** [liuxinyu95/unplugged#37]
https://github.com/liuxinyu95/unplugged/blob/d6b992e48bb11eb8c38db91dd836dcea130255ee/appendix/preface/preface-en.tex#L222
There is a double "and" in this line...

**Comment by liuxinyu95** [comment]
Thanks a lot for pointing out this issue. I made the correction:
https://github.com/liuxinyu95/unplugged/commit/48c924239198336edc1629833bae91660e2f2373
