### ISSUE TITLE
ch2.5勘误

### ISSUE THREAD

**Issue by hayahayao** [liuxinyu95/unplugged#39]
```
& \xrightarrow{\beta} & (f \mapsto f \mapsto f\ p\ q)\ (a \mapsto b \mapsto a) \\
```

[line 1045](https://github.com/liuxinyu95/unplugged/blob/master/recursion/recursion-zh-cn.tex#L1045) 

这里似乎多写了一个箭头，应为`& \xrightarrow{\beta} & (f \mapsto f\ p\ q)\ (a \mapsto b \mapsto a) \\`

**Comment by liuxinyu95** [comment]
多谢指出这个错误，已修正：
https://github.com/liuxinyu95/unplugged/commit/392b3a72621fd89b4213942d1ee321eced2e075f
