### ISSUE TITLE
疑似typo

### ISSUE THREAD

**Issue by myfreess** [liuxinyu95/unplugged#42]
https://github.com/liuxinyu95/unplugged/blob/master/category-theory/category-zh-cn.tex

3443行处“我们没能介绍伴随(junction)的概念”疑似为Adjunction

**Comment by liuxinyu95** [comment]
非常感谢指出这个问题，已修改：https://github.com/liuxinyu95/unplugged/commit/e7e482dcdee6c83d1cbaaf7c174b78b2b8bdac3e

**Comment by myfreess** [comment]
非常感谢您为中文计算机科学科普做出的贡献!
