### ISSUE TITLE
笔误-中文版-第1章 练习1.2

### ISSUE THREAD

**Issue by ZhiweiYAN** [liuxinyu95/unplugged#49]
中文版-第1章 练习1.2 的第4题：

如何利用皮亚诺公里验证 3 + 147 = 150？
应为：公里 -> 公理

**Comment by liuxinyu95** [comment]
非常感谢！我搜索并修改了全部这一拼音输入法造成的错误。
https://github.com/liuxinyu95/unplugged/commit/bb04c041749d59b512e9e742aa3a87802cfc53a5
