### ISSUE TITLE
3.1.2 幺半群与半群 勘误

### ISSUE THREAD

**Issue by Richard-Zheng** [liuxinyu95/unplugged#58]
> 定义 3.1.2. 幺半群是一个集合 S 和其上定义的二元运算 ·，它们遵循两条公理：
>
> 1. 结合性公理：S 中和任何三个元素满足 (a · b) · c = a · (b · c)；
> 2. 单位元公理：S 中存在一个元素 e，使得对任何 a · e = e · a = **e**。

此处 e 应为 a.

另外，感谢作者对计算机科学和数学普及作出的贡献。

**Comment by liuxinyu95** [comment]
非常感谢指出，这个问题已经在euler分枝上改正了：
https://github.com/liuxinyu95/unplugged/blob/euler/algebra/algebra-zh-cn.tex#L361
我会在2023年初把euler分枝合并到主分枝。

再次感谢！
