### ISSUE TITLE
Chapter 3 勘误

### ISSUE THREAD

**Issue by yjhmelody** [liuxinyu95/unplugged#6]
![image](https://user-images.githubusercontent.com/16250688/46451035-facd2300-c7c6-11e8-8371-1edd629a5ae3.png)

**Comment by yjhmelody** [comment]
![image](https://user-images.githubusercontent.com/16250688/46451397-b478c380-c7c8-11e8-83ab-40345b1940c1.png)
括号不一致

**Comment by liuxinyu95** [comment]
非常感谢，已经修改了这两处问题：
[commit](https://github.com/liuxinyu95/unplugged/commit/e77d31450a3a9b9c3d6c62415bb787fdad0535b7)
