### ISSUE TITLE
Typo in Proof of Theorem 3.1.9

### ISSUE THREAD

**Issue by chirsz-ever** [liuxinyu95/unplugged#60]
https://github.com/liuxinyu95/unplugged/blob/65f423e97063794c2b09fb69c0c3cfe6bf9ca2ef/algebra/algebra-zh-cn.tex#L1015-L1024

此处“充分性”和“必要性”似乎写反了？

**Comment by liuxinyu95** [comment]
Hello,

充分性：H 是 G的子群  ==> a, b in H 则 ab^{-1} in H
必要性：a, b in H 则 ab^{-1} in H  ==> H是G的子群。

没有反。

**Comment by chirsz-ever** [comment]
设 P : `forall a b in H, ab^{-1} in H`，Q : `H 是 G 子群`

第 1016 行换一下语序是 P 是 Q 的充分必要条件，那接下来所述的充分性应当是 P 能推出 Q 才对吧？

**Comment by liuxinyu95** [comment]
我明白你的意思了。

**Comment by liuxinyu95** [comment]
已修改：https://github.com/liuxinyu95/unplugged/commit/03aabdca0f8886ad7dbcb67cd0e43019e2206a47
