### ISSUE TITLE
第1章第4节 勘误

### ISSUE THREAD

**Issue by sunpeng1995** [liuxinyu95/unplugged#9]
![c1s4cn](https://user-images.githubusercontent.com/9283792/56847466-c7421980-690d-11e9-8408-8c86ef8ff03d.PNG)

中文版此处有误，应为 对自然数m取n次幂。
英文版此处正确。

**Comment by liuxinyu95** [comment]
非常感谢，已修改：
https://github.com/liuxinyu95/unplugged/commit/5feeb911778f07e53303a715574bcf6f26b119ea
